/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IGovernerFactoryInterface extends Interface {
  getFunction(nameOrSignature: "governer" | "hasGoverner"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "GovernerCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "governer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasGoverner",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "governer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasGoverner",
    data: BytesLike
  ): Result;
}

export namespace GovernerCreatedEvent {
  export type InputTuple = [
    governerId: BigNumberish,
    governer: AddressLike,
    founder: AddressLike,
    descriptionHash: BytesLike
  ];
  export type OutputTuple = [
    governerId: bigint,
    governer: string,
    founder: string,
    descriptionHash: string
  ];
  export interface OutputObject {
    governerId: bigint;
    governer: string;
    founder: string;
    descriptionHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IGovernerFactory extends BaseContract {
  connect(runner?: ContractRunner | null): IGovernerFactory;
  waitForDeployment(): Promise<this>;

  interface: IGovernerFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  governer: TypedContractMethod<[governerId: BigNumberish], [string], "view">;

  hasGoverner: TypedContractMethod<[governer: AddressLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "governer"
  ): TypedContractMethod<[governerId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "hasGoverner"
  ): TypedContractMethod<[governer: AddressLike], [boolean], "view">;

  getEvent(
    key: "GovernerCreated"
  ): TypedContractEvent<
    GovernerCreatedEvent.InputTuple,
    GovernerCreatedEvent.OutputTuple,
    GovernerCreatedEvent.OutputObject
  >;

  filters: {
    "GovernerCreated(uint256,address,address,bytes32)": TypedContractEvent<
      GovernerCreatedEvent.InputTuple,
      GovernerCreatedEvent.OutputTuple,
      GovernerCreatedEvent.OutputObject
    >;
    GovernerCreated: TypedContractEvent<
      GovernerCreatedEvent.InputTuple,
      GovernerCreatedEvent.OutputTuple,
      GovernerCreatedEvent.OutputObject
    >;
  };
}
