/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICampaign } from "./ICampaign";
export type { IGovernor } from "./IGovernor";
export type { IGovernorFactory } from "./IGovernorFactory";
export type { IGovernorVotes } from "./IGovernorVotes";
export type { IRevenuePool } from "./IRevenuePool";
export type { IRevenuePoolFactory } from "./IRevenuePoolFactory";
export type { IVotes } from "./IVotes";
