/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICampaign,
  ICampaignInterface,
} from "../../../contracts/interfaces/ICampaign";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "campaignId",
        type: "uint256",
      },
    ],
    name: "CampaignLaunched",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "campaignId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "governorId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "Fund",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "campaignId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "governorIds",
        type: "uint256[]",
      },
    ],
    name: "FundAllocated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "campaignId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "governorId",
        type: "uint256",
      },
    ],
    name: "GovernorJoined",
    type: "event",
  },
  {
    inputs: [],
    name: "allocateFunds",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "campaignId",
        type: "uint256",
      },
    ],
    name: "campaignData",
    outputs: [
      {
        internalType: "uint256",
        name: "totalFunded",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "descriptionHash",
        type: "bytes32",
      },
      {
        internalType: "uint64",
        name: "fundStart",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "fundDuration",
        type: "uint64",
      },
      {
        internalType: "bool",
        name: "allocated",
        type: "bool",
      },
      {
        internalType: "uint256[]",
        name: "governorIds",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "founder",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "governorId",
        type: "uint256",
      },
    ],
    name: "fund",
    outputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "governorId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "governor",
        type: "address",
      },
    ],
    name: "joinCampaign",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "descriptionHash",
        type: "bytes32",
      },
    ],
    name: "launchCampaign",
    outputs: [
      {
        internalType: "uint256",
        name: "campaignId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICampaign__factory {
  static readonly abi = _abi;
  static createInterface(): ICampaignInterface {
    return new Interface(_abi) as ICampaignInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ICampaign {
    return new Contract(address, _abi, runner) as unknown as ICampaign;
  }
}
