/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IGovernerFactory,
  IGovernerFactoryInterface,
} from "../../../contracts/interfaces/IGovernerFactory";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "governerId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "governer",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "founder",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "descriptionHash",
        type: "bytes32",
      },
    ],
    name: "GovernerCreated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "governerId",
        type: "uint256",
      },
    ],
    name: "governer",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "governer",
        type: "address",
      },
    ],
    name: "hasGoverner",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IGovernerFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IGovernerFactoryInterface {
    return new Interface(_abi) as IGovernerFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IGovernerFactory {
    return new Contract(address, _abi, runner) as unknown as IGovernerFactory;
  }
}
